%%{init: {'theme':'base'}}%%
xychart-beta
    title "📈 Sales Growth Analysis"
    x-axis ["Period 1", "Period 2", "Period 3", "Period 4", "Period 5", "Period 6", "Period 7", "Period 8", "Period 9", "Period 10", "Period 11", "Period 12"]
    y-axis "Value"
    line [101.62, 89.79, 34.44, 734.77, 323.22, 353.07, 146.03, 174.76, 472.44, 518.32, 437, 460.79]