%%{init: {'theme':'base'}}%%
xychart-beta
    title "Product Categories"
    x-axis ["Point 1", "Point 3", "Point 5", "Point 7", "Point 9", "Point 11"]
    y-axis "Value"
    bar [450, 320, 280, 195, 155, 210]