%%{init: {'theme':'base'}}%%
xychart-beta
    title "Department Performance"
    x-axis ["Point 1", "Point 2", "Point 3", "Point 4", "Point 5", "Point 7", "Point 8", "Point 9", "Point 10", "Point 11", "Point 13", "Point 14", "Point 15", "Point 16", "Point 17", "Point 19", "Point 20", "Point 21", "Point 22", "Point 23", "Point 25", "Point 26", "Point 27", "Point 28", "Point 29"]
    y-axis "Value"
    line [78, 82, 85, 88, 91, 72, 75, 78, 80, 83, 85, 87, 89, 91, 93, 70, 73, 75, 77, 80, 80, 82, 84, 86, 88]