%%{init: {'theme':'base'}}%%
xychart-beta
    title "🌐 Multi-Series Line Chart"
    x-axis ["Point 1", "Point 2", "Point 3", "Point 4", "Point 5", "Point 6"]
    y-axis "Value"
    line [120, 118, 122, 130, 138, 145]