%%{init: {'theme':'base'}}%%
xychart-beta
    title "Monthly Sales Trend"
    x-axis ["Point 1", "Point 3", "Point 5", "Point 7", "Point 9", "Point 11", "Point 13", "Point 15", "Point 17", "Point 19", "Point 21", "Point 23"]
    y-axis "Value"
    line [45, 52, 48, 61, 58, 72, 69, 75, 82, 79, 88, 95]