%%{init: {'theme':'base'}}%%
pie title Market Share
    "Apple" : 31
    "Samsung" : 23
    "Google" : 18
    "Microsoft" : 15
    "Others" : 13
    "Apple" : 31
    "Samsung" : 23
    "Google" : 18
    "Microsoft" : 15
    "Others" : 13